version: '3.8'
services:
  app:
    build:
      args:
        user: sondv
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: php-app
    restart: unless-stopped
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d/
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: inject_demodb
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: sql_injection
      MYSQL_PASSWORD: foobar
    ports:
      - "9906:3306"
    volumes:
      - ./database/photo-gallery-laravel-database.sql:/docker-entrypoint-initdb.d/dump.sql
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
#Docker Networks
networks:
  photos:
    driver: bridge
